import{i as a,S as f}from"./assets/vendor-5b791d57.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const m="https://pixabay.com/api",d="41971380-5e7df6cf95dc1cfc66e370c4e",c={form:document.getElementById("search-form"),resultContainer:document.getElementById("result-container"),loader:document.querySelector(".loader")};c.form.addEventListener("submit",h);function h(t){t.preventDefault();const o=t.currentTarget,i=o.elements.picture.value;L(),p(i).then(s=>{const e=s.hits;e.length===0&&a.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}),y(e)}).catch(s=>{console.log(s),a.error({position:"topRight",message:"Failed to fetch images. Please try again later."})}).finally(()=>{o.reset(),P()})}function p(t){const o=new URLSearchParams({key:d,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15});return fetch(`${m}?${o}`).then(i=>{if(!i.ok)throw new Error(i.statusText);return i.json()})}let g=new f(".gallery a",{captionsData:"alt",captionDelay:250});function y(t){const o=t.map(({webformatURL:i,largeImageURL:s,tags:e,likes:r,views:n,comments:l,downloads:u})=>`<li class="gallery-item">
            <a href="${s}">
  <img class="gallery-image" src="${i}" alt="${e}" width="370" heigth="300"></a>
  <ul class="info-list">
    <li class="info-item">Likes: ${r}</li>
    <li class="info-item">Views: ${n}</li>
    <li class="info-item">Comments: ${l}</li>
    <li class="info-item">Downloads: ${u}</li>
  </ul>
</li>`).join("");c.resultContainer.innerHTML=o,g.refresh()}function L(){const t=document.querySelector(".loader");t&&t.classList.add("visible")}function P(){const t=document.querySelector(".loader");t&&t.classList.remove("visible")}
//# sourceMappingURL=commonHelpers.js.map
